name: Publish Markdown to Wiki

on:
  workflow_dispatch:
  push:
    paths:
      - '**/*.md'

jobs:
  publish-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Clone wiki repo
        run: |
          git clone https://github.com/${{ github.repository }}.wiki.git wiki

      - name: Copy markdown files
        run: |
          find . -name "*.md" -not -path "./wiki/*" -exec cp {} wiki/ \;

      - name: Commit and push to wiki
        run: |
          cd wiki
          git add .
          git commit -m "Update wiki from repo markdown files" || echo "No changes to commit"
          git push
